/**
 * Label generation response types
 * Carrier-agnostic types for batch label creation with file mapping
 */

/**
 * Physical label file returned by the carrier or produced by adapter processing
 * 
 * Represents an actual file artifact (PDF, ZPL, etc.) that can be stored, transmitted, or displayed.
 * Multiple parcels may reference the same file (e.g., single PDF with multiple labels).
 */
export interface LabelFileResource {
  /**
   * Unique identifier for this file (UUID, generated by adapter)
   * Used to link LabelResult items to their corresponding file(s)
   */
  id: string;

  /**
   * Optional direct URL to access the file
   * Could be a presigned URL, CDN URL, or temporary public URL
   * Integrators typically replace this with their own CDN URL after upload
   */
  url?: string;

  /**
   * Optional inline data URL for small files
   * Format: data:application/pdf;base64,...
   * Avoid for large files; prefer url instead
   * Useful for development/testing or very small labels
   */
  dataUrl?: string;

  /**
   * MIME type of the file (e.g., "application/pdf", "application/x-zpl")
   */
  contentType: string;

  /**
   * Size of the file in bytes (if known)
   */
  byteLength?: number;

  /**
   * Number of pages in the file (relevant for PDF)
   */
  pages?: number;

  /**
   * Page orientation if known (e.g., portrait A7, landscape A6)
   */
  orientation?: 'portrait' | 'landscape';

  /**
   * Carrier-specific metadata (e.g., Foxpost size, testMode, compression)
   */
  metadata?: Record<string, unknown>;

  /**
   * Checksum for integrity verification (e.g., SHA256 hex)
   */
  checksum?: string;

  /**
   * ISO 8601 timestamp when this URL or file expires (if presigned/temporary)
   */
  expiresAt?: string;
}

/**
 * Per-parcel label result
 * Describes the outcome of label generation for a single input parcel
 * 
 * Maintains strict 1:1 correspondence with input parcel IDs (same order).
 * References files via fileId for carriers that produce one or many files.
 */
export interface LabelResult {
  /**
   * The input parcel carrier ID that was requested
   * Matches the request's parcelCarrierIds[i]
   */
  inputId: string;

  /**
   * Status of this label generation attempt
   * - 'created': label was generated successfully
   * - 'failed': label generation failed (see errors)
   * - 'skipped': label was skipped (e.g., carrier limitation)
   */
  status: 'created' | 'failed' | 'skipped';

  /**
   * Reference to LabelFileResource.id if status === 'created'
   * Multiple LabelResult items may reference the same fileId (single PDF with multiple labels)
   */
  fileId?: string;

  /**
   * Page range in the referenced file where this parcel's label(s) reside
   * Useful when file contains multiple pages and each label occupies one or more pages
   * Example: { start: 1, end: 1 } for single-page label, { start: 2, end: 2 } for second page
   */
  pageRange?: {
    start: number;
    end: number;
  };

  /**
   * Errors if status === 'failed'
   */
  errors?: Array<{
    code?: string;
    message: string;
    field?: string;
  }>;

  /**
   * Raw carrier response for this specific parcel (if available)
   */
  raw?: unknown;
}

/**
 * Batch label creation response
 * 
 * Combines:
 * - files: the actual file artifacts (may be one or many)
 * - results: per-input outcome and file mapping
 * - summary: overall success/failure counts
 * 
 * @example Foxpost (single PDF, multiple labels)
 * ```
 * {
 *   files: [{
 *     id: "uuid-1",
 *     dataUrl: "data:application/pdf;base64,...",
 *     contentType: "application/pdf",
 *     pages: 3,
 *     orientation: "portrait",
 *     metadata: { size: "A7", testMode: true }
 *   }],
 *   results: [
 *     { inputId: "CLFOX001", status: "created", fileId: "uuid-1", pageRange: { start: 1, end: 1 } },
 *     { inputId: "CLFOX002", status: "created", fileId: "uuid-1", pageRange: { start: 2, end: 2 } },
 *     { inputId: "CLFOX003", status: "created", fileId: "uuid-1", pageRange: { start: 3, end: 3 } }
 *   ],
 *   successCount: 3,
 *   failureCount: 0,
 *   totalCount: 3,
 *   allSucceeded: true,
 *   ...
 * }
 * ```
 * 
 * @example Multi-file carrier (hypothetical)
 * ```
 * {
 *   files: [
 *     { id: "uuid-1", url: "s3://bucket/label-001.pdf", ... },
 *     { id: "uuid-2", url: "s3://bucket/label-002.pdf", ... }
 *   ],
 *   results: [
 *     { inputId: "PARCEL001", status: "created", fileId: "uuid-1" },
 *     { inputId: "PARCEL002", status: "created", fileId: "uuid-2" }
 *   ],
 *   ...
 * }
 * ```
 */
export interface CreateLabelsResponse {
  /**
   * Per-parcel results from the batch operation
   * One LabelResult per input parcelCarrierId, in the same order
   * Maintains strict 1:1 correspondence with request input
   */
  results: LabelResult[];

  /**
   * File artifacts returned by carrier or produced by adapter
   * Optional: may be empty if all labels failed
   * May contain one file (Foxpost) or multiple files (other carriers)
   */
  files?: LabelFileResource[];

  /**
   * Number of labels that succeeded (status === 'created')
   */
  successCount: number;

  /**
   * Number of labels that failed (status === 'failed')
   */
  failureCount: number;

  /**
   * Total number of labels processed
   */
  totalCount: number;

  /**
   * Whether all labels succeeded
   * True only if failureCount === 0 && totalCount > 0
   */
  allSucceeded: boolean;

  /**
   * Whether all labels failed
   * True only if successCount === 0 && totalCount > 0
   */
  allFailed: boolean;

  /**
   * Whether operation had mixed results (some succeeded, some failed)
   * True only if successCount > 0 && failureCount > 0
   */
  someFailed: boolean;

  /**
   * Human-readable summary of the results
   * Examples:
   * - "All 5 labels generated successfully"
   * - "3 labels generated, 2 failed"
   * - "All labels failed"
   */
  summary: string;

  /**
   * Full raw carrier response from the HTTP call
   * For batch label endpoints, this typically contains:
   * - Binary PDF data (if carrier returned bytes)
   * - Response metadata (headers, status code)
   * - Error details
   * Useful for debugging, auditing, and later storage
   */
  rawCarrierResponse?: unknown;
}
