import type { Shipment, Parcel } from '../types/index.js';
import type { CarrierResource } from '../interfaces/index.js';

/**
 * DomainEvent
 * Immutable domain event for audit logging
 */
export interface DomainEvent {
  /** Unique event ID (optional, can be generated by store) */
  id?: string;

  /** Event type */
  type:
    | "SHIPMENT_CREATED"
    | "PARCEL_CREATED"
    | "SHIPMENT_CLOSED"
    | "LABEL_GENERATED"
    | "LABEL_VOIDED"
    | "TRACKING_UPDATED"
    | "ERROR_OCCURRED";

  /** When the event occurred */
  timestamp?: Date;

  /** Internal entity ID */
  internalId: string;

  /** Carrier ID (if applicable) */
  carrierId?: string;

  /** Associated resource */
  resource?: CarrierResource;

  /** Event details */
  details?: Record<string, unknown>;
}

/**
 * Store interface
 * Pluggable persistence layer
 * Integrators implement this for their storage backend (Postgres, SQLite, DynamoDB, etc.)
 */
export interface Store {
  /**
   * Save or update an internal shipment record
   */
  saveShipment(shipment: Shipment): Promise<void>;

  /**
   * Retrieve a shipment by ID
   */
  getShipment(id: string): Promise<Shipment | null>;

  /**
   * Save an internal parcel record
   */
  saveParcel(parcel: Parcel): Promise<void>;

  /**
   * Retrieve a parcel by ID
   */
  getParcel(id: string): Promise<Parcel | null>;

  /**
   * Save a carrier resource mapping
   * This creates a record linking an internal resource to its carrier ID
   * Examples:
   *   saveCarrierResource(shipmentId, "shipment", { carrierId: "foxpost-12345", raw: {...} })
   *   saveCarrierResource(parcelId, "parcel", { carrierId: "fp-parcel-789", status: "created" })
   */
  saveCarrierResource(
    internalId: string,
    resourceType: "shipment" | "parcel" | "label",
    resource: CarrierResource
  ): Promise<void>;

  /**
   * Retrieve a carrier resource by internal ID
   */
  getCarrierResource(
    internalId: string,
    resourceType: string
  ): Promise<CarrierResource | null>;

  /**
   * Append an immutable domain event to the audit log
   */
  appendEvent(internalId: string, event: DomainEvent): Promise<void>;

  /**
   * Retrieve events for an entity (useful for debugging and compliance)
   */
  getEvents(internalId: string): Promise<DomainEvent[]>;
}
